config/routes.rb
Nomster::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root 'places#index'

  resources :places do
    resources :comments, :only => :create
    resources :photos, :only => :create
  end
  resources :users, :only => :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :place
	after_create :send_comment_email

	letsrate_rateable "overall"

	def send_comment_email
		NotificationMailer.comment_added(self).deliver
	end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	mount_uploader :picture, PictureUploader

	belongs_to :place
	belongs_to :user
end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :photos
	
	geocoded_by :address
	after_validation :geocode

	validates :name, :address, :description, :presence => true
	validates :name, length: { minimum: 3 }
	validates :description, length: { minimum: 15, maximum: 1000 }
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@place = Place.find(params[:place_id])
		@place.comments.create(comment_params.merge(:user => current_user))
		redirect_to place_path(@place)
	end

	private

	def comment_params
		params.require(:comment).permit(:message, :rating)
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!
	def create
		@place = Place.find(params[:place_id])
		@place.photos.create(photo_params)
		redirect_to place_path(@place)
	end

	private

	def photo_params
		params.require(:photo).permit(:caption, :picture)
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

	def index
		@places = Place.order("name")

		@places = Kaminari.paginate_array(@places).page(params[:page]).per(5)
	end

	def new
		@place = Place.new
	end

	def create
		@place = current_user.places.create(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :new, :status => :unprocessable_entity
		end
	end

	def show
		@place = Place.find(params[:id])
		@comment = Comment.new
		@photo = Photo.new
	end

	def edit
		@place = Place.find(params[:id])

		if @place.user != current_user
			return render :text => 'Not Allowed', :status => :forbidden
		end
	end

	def update
		@place = Place.find(params[:id])

		if @place.user != current_user
			return render :text => 'Not Allowed', :status => :forbidden
		end

		@place.update_attributes(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :edit, :status => :unprocessable_entity
		end
	end

	def destroy
		@place = Place.find(params[:id])
		if @place.user != current_user
			return render :text => 'Not Allowed', :status => :forbidden
		end

		@place.destroy
		redirect_to root_path
	end

	private

	def place_params
		params.require(:place).permit(:name, :description, :address)
	end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_i, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Where the Phở? | Find the best phở shops near you!</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="google-site-verification" content="Z7sJLnfRIEEK1an4HnnffUnyShbsqqKEhrLwhL76z_o" />
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
	<div class="container-fluid">
		<!--Brand and toggle get grouped for better mobile display-->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to root_path, :class => 'navbar-brand' do %>
				W<span>here the </span>P<span>h&#376;</span>?
			<% end %>
		</div>

	<!-- collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li>
				<%= link_to new_place_path do %>
				<i class="glyphicon glyphicon-plus-sign"></i>
				New Place
				<% end %>
			</li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
				<li><%= link_to 'My Profile', user_path(current_user) %></li>
				<li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
			<% else %>
				<li><%= link_to 'Sign In', new_user_session_path %></li>
				<li><%= link_to 'Sign Up', new_user_registration_path %></li>
			<% end %>
  		</ul>
	</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
<p class="alert alert-info"><%= notice %></p>
<% end %>

<% if alert.present? %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-m-6 col-m-offset-3">
	<h2 style="text-align: center">Edit Your Place</h2>
	<br />
	<%= simple_form_for @place do |f| %>
		<%= f.input :name %>
		<%= f.input :address %>
		<%= f.input :description %>
		<br />
		<div class="pull-right">
			<%= f.submit 'Update', :class => 'btn btn-primary' %>
			<%= link_to 'Delete', place_path(@place), :method => :delete, :data => {:confirm => 'Are you sure you want to PERMANENTLY delete this place? WARNING: This action cannot be undone.'}, :class => 'btn btn-danger' %>
			<%= link_to 'Cancel', root_path, :data => {:confirm => 'Are you sure you don\'t want to update this place?'}, :class => 'btn btn-warning' %>
		</div>
	<% end %>
</div>

app/views/places/index.html.erb
<div class="slider-box col-xs-12 col-sm-8 col-sm-offset-2 col-m-8 col-m-offset-2">

  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <!-- <li data-target="#carousel-example-generic" data-slide-to="2"></li> -->
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active slider1">
        <%# image_tag 'slider1.jpg', :class => 'img-responsive' %>
        <div class="carousel-caption">
          Find the best phở places near you!
        </div>
      </div>
      <div class="item slider2">
        <%# image_tag 'slider2.jpg', :class => 'img-responsive' %>
        <div class="carousel-caption">
        	Looking for phở?
        </div>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>

</div>

<% @places.each do |place| %>
	<div class="booyah-box col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-m-8 col-m-offset-2">
		<h1><%= link_to place.name, place_path(place) %></h1>
		<em><%= place.address %></em><br /><br />
		<p><%= place.description %></p><br />
<!-- show photo -->
    <% if place.photos.last.present? %>
        <div class="previewpic text-center col-xs-12 col-sm-10 col-sm-offset-1">
          <%= image_tag place.photos.last.picture %>
        </div>
      <div class="clear"></div>
      <br />
    <% end %>
<!-- end show photo -->
		<% if place.user.present?%>
			<small>Submitted by <%= place.user.email %></small>
		<% end %>
			<% if place.comments.present? %>
			<div class="col-xs-12">
				<br />
				<blockquote>
					<% if place.comments.last.rating.present? %>
<!--insert stars logic here-->
					 [stars] - 
					<% end %>
					<%= place.comments.last.message %>
					<small><%= place.comments.last.user.email %></small>
				</blockquote>
			</div>
			<% end %>
		</div>
	<% end %>

<div class="pages_container col-xs-12">
<div class="pages">
<%= paginate @places, :theme => 'twitter-bootstrap-3' %>
</div>
</div>

app/views/places/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-m-6 col-m-offset-3">
	<h2 style="text-align: center">Enter Your Place Details</h2>
	<br />
	<%= simple_form_for @place do |f| %>
		<%= f.input :name %>
		<%= f.input :address %>
		<%= f.input :description %>
		<br />
		<div class="pull-right">
			<%= link_to 'Nevermind', root_path, :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-warning' %>
			<%= f.submit 'Create', :class => 'btn btn-primary' %>
		</div>
	<% end %>
</div>

app/views/places/show.html.erb
	<div class="booyah-box col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-m-8 col-m-offset-2">
		<h1><%= @place.name %></h1>
		<em><%= @place.address %></em><br /><br />
		<p><%= @place.description %></p><br />
<!--stars stuff-->
			<%= @place.comments.average(:rating) %>


		<% if @place.latitude.present? && @place.longitude.present? %>
		  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
		  <script>
		    function initialize() {
		      var myLatlng = new google.maps.LatLng(<%= @place.latitude %>, <%= @place.longitude %>);
		      var mapOptions = {
		        zoom: 13,
		        center: myLatlng
		      };
		      var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

		      var marker = new google.maps.Marker({
		        position: myLatlng,
		        map: map,
		        title: 'Hello World!'
		      });
		    }

		    google.maps.event.addDomListener(window, 'load', initialize);

		  </script>

		  <div id="map-canvas"></div>
		<% end %>

		<br />

		<% if @place.user.present?%>
			<small>Submitted by <%= @place.user.email %></small>
		<% end %>
		<div class="pull-right">
			<% if current_user && current_user == @place.user %>
				<%= link_to 'Edit', edit_place_path(@place), :class => 'btn btn-primary' %>
			<% end %>
		</div>
		<br /><br />
		<hr>
		<div class="clear"></div>
		<div class="text-center">
		<h2>Comments</h2>
		</div>
		<br />
		<!-- Button trigger modal -->
		<div class="text-center">
<button class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  <span class="glyphicon glyphicon-comment"></span> Add a Comment
</button>
<button class="btn btn-primary" data-toggle="modal" data-target="#myModal2">
  <span class="glyphicon glyphicon-camera"></span> Add a Photo
</button>
		</div>

<!-- Comment Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a Comment</h4>
      </div>
        <%= simple_form_for @comment, :url => place_comments_path(@place) do |f| %>
        <div class="modal-body">
			<%= f.input :message %>
<!--stars input-->
			<%= 
			f.input(
				:rating,
				class: "rating"
			)
			%>
		</div>
			<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			<%= f.submit "Submit Comment", :class => 'btn btn-primary' %>
			</div>
		<% end %>
    </div>
  </div>
</div>

<!-- Photo Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a Photo</h4>
      </div>
        <%= simple_form_for @photo, :url => place_photos_path(@place) do |f| %>
        <div class="modal-body">
        	<%= f.file_field :picture, :label => 'Select a photo:'  %>
        	<br />
			<%= f.input :caption %>
		</div>
			<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			<%= f.submit "Add a Photo", :class => 'btn btn-primary' %>
			</div>
		<% end %>
    </div>
  </div>
</div>

<br />
			
			<div class="collapse" id="showcomments">
			<% @place.comments.each do |comment| %>
			<div class="col-xs-12 col-sm-6">
				<br />
				<blockquote>
<!--stars blockquote-->
					<%= 
						number_field_tag(
							:comment,
							comment.rating,
							class: "rating",
							disabled: true,
							data: {
								size: "xs",
								step: 1,
								show_clear: false,
								show_caption: false
							}
						)
						%>
						 -
					<%= comment.message %>
					<small><%= comment.user.email %></small>
				</blockquote>
			</div>
			<% end %>
			<div class="clear"></div>
			<br /><br />
		</div>
		<div class="text-center">
      <a class="btn btn-warning" data-toggle="collapse" data-target="#showcomments" id="showComments">
        <span class="glyphicon glyphicon-collapse-down"></span>
        <span class="text">Show Comments</span>
      </a>
	</div>
<!--button jquery -->
	<script>
		$('#showComments').click(function(){
        // Could have made an $icon_span, but we only use it once this way
        $(this).
          find('.glyphicon').
          toggleClass('glyphicon-collapse-down glyphicon-collapse-up');

        $text_span = $(this).find('.text');

        if ($text_span.text() === 'Show Comments') {
          $text_span.text('Hide Comments');
        } else if ($text_span.text() === 'Hide Comments') {
          $text_span.text('Show Comments');
        }
		});
	</script>
<hr />
	<div class="text-center">
		<h2>Photos</h2>
	</div>
	<br />
	<% @place.photos.each do |photo| %>
		<div class="text-center col-xs-12 col-sm-6">
			<%= image_tag photo.picture %>
			<br />
			<div class="captionbox">
				<%= photo.caption %>
			</div>
			<br />
		</div>
	<% end %>
	<div class="clear"></div>

</div>

<script>
		  $("#myModal").on("show.bs.modal", function(){
		  		console.log("asdf");
		  		$("#comment_rating").rating({
		  			"size":"xs"
		  		});
		  });
</script>

app/views/users/show.html.erb
<div class="booyah-box">
	<div class="col-xs-4">
		<%= image_tag 'user.png' %>
	</div>

	<div class="col-xs-6">
		<h1><%= @user.email %>'s Profile</h1>
		<h3>Member since <%= @user.created_at.strftime("%B %d, %Y") %>.</h3>
		<h4>Has made <%= @user.comments.count %> comment(s).</h4>
		<h4>Has submitted <%= @user.comments.count %> review(s).</h4>
		<h4>• <%= @user.comments.where(:rating => '5_stars').count %> 5-star review(s).
	</div>
	<div class="clear"></div>
</div>
<br /><br />
<h1 class="text-center"><%= @user.email %>'s Comments</h1>
<br /><br />

<% @user.comments.each do |comment| %>
	<div class="col-xs-12 col-sm-6">
		<h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
			<blockquote>
				<% comment.rating.times do %>
							<%= "★" %>
				<% end %>
						 -
				<%= comment.message %>
				<small><%= comment.user.email %></small>
			</blockquote>
		</div>
<% end %>
<div class="clear"></div>
<br /><br />


<h1 class="text-center"><%= @user.email %>'s Places</h1>
<br /><br />
<% @user.places.each do |place| %>
	<div class="booyah-box col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-m-8 col-m-offset-2">
		<h1><%= link_to place.name, place_path(place) %></h1>
		<em><%= place.address %></em><br /><br />
		<p><%= place.description %></p><br />

		<% if place.user.present?%>
			<small>Submitted by <%= place.user.email %></small>
		<% end %>
			<% if place.comments.present? %>
			<div class="col-xs-12">
				<br />
				<blockquote>
					<% if place.comments.last.rating.present? %>
						<% place.comments.last.rating.times do |i| %>
						<!-- can't get this to work -->
							<%= "★" %>
						<% end %> -
					<% end %>
					<%= place.comments.last.message %>
					<small><%= place.comments.last.user.email %></small>
				</blockquote>
			</div>
			<% end %>
		</div>
	<% end %>
<br /> <br />